### PR TITLE
#156004609 Pass Data From MainActivity to DetailActivity

### PR DESCRIPTION
**Pull request by evamaina**
#### What does this PR do?
- Pass data from MainActivity to DetailActivity.
#### Description of Task to be completed?
- On clicking a single user item on the MainActivity ListView it should launch the DetailActivity with the data pertaining to the particular user.
#### Any background context you want to provide?
- Clicking on the url directs you to the user profile that displays the number of repositories, organization, and followers.

#### What are the relevant pivotal tracker stories?
[#156004609](https://www.pivotaltracker.com/story/show/156004609)

#### Screenshots
image

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
Make a video of moving from the MainActivity to the detail activity. Then use this https://ezgif.com/video-to-gif to convert the video to a gif, and include that gif in your PR in the screenshot area instead of those pictures. 

Use this resource https://developer.android.com/studio/debug/am-video to learn how to make the video in Android Studio.

**Comment by evamaina** [comment]
> Make a video of moving from the MainActivity to the detail activity. Then use this https://ezgif.com/video-to-gif to convert the video to a gif, and include that gif in your PR in the screenshot area instead of those pictures.
> 
> Use this resource https://developer.android.com/studio/debug/am-video to learn how to make the video in Android Studio.

on it

**Comment by evamaina** [comment]
> > Make a video of moving from the MainActivity to the detail activity. Then use this https://ezgif.com/video-to-gif to convert the video to a gif, and include that gif in your PR in the screenshot area instead of those pictures.
> > Use this resource https://developer.android.com/studio/debug/am-video to learn how to make the video in Android Studio.
> 
> on it

done

**Comment by cmplx-xyttmt** [comment]
LGTM

**Pull request merged**
